name: 'Terraform GitHub Actions'
on: [push, pull_request]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Terraform Format'
        uses: arwa123456/arwastage@main
        with:
         tf_actions_version: 0.12.18
         tf_actions_subcommand: init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      

     
