name: 'Terraform GitHub Actions'
on: [push, pull_request]
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Terraform Format'
        uses: arwa123456/STAGEDEV@main
        with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          tf_actions_subcommand: ['init','plan','apply']
  
