name: 'Terraform GitHub Actions'
on: [push, pull_request]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-action@main
        with:
         tf_actions_version: 1.2.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      

     
