name: 'Terraform GitHub Actions'
on: [push, pull_request]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
         tf_actions_version: 0.12.18
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan
        # On push to main, build or change infrastructure according to Terraform configuration files
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      

     
