name: 'Terraform GitHub Actions'
on: [push, pull_request]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Terraform Format'
        uses: arwa123456/STAGEDEV@main   
        with:
         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
         tf_actions_version: 1.2.5
      - name: 'Terraform Init'
        run: terraform init
      - name: Terraform Plan
        run: terraform plan
        # On push to main, build or change infrastructure according to Terraform configuration files
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        
    # Build the Docker image
      - name: Build
        run: |
         docker build -t "$REGISTRY_HOSTNAME"/"$GKE_PROJECT"/"$IMAGE":"$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" .

    # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
         docker push $REGISTRY_HOSTNAME/$GKE_PROJECT/$IMAGE:$GITHUB_SHA

    # Set up kustomize
      - name: Set up Kustomize
        run: |
         curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
         chmod u+x ./kustomize

    # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |
