name: 'Terraform GitHub Actions'
on: [push, pull_request]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: arwa123456/arwastage@main   
        with:
         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
         tf_actions_version: 1.2.5
      - name: 'Terraform Init'
        run: terraform init
      - name: Terraform Plan
        run: terraform plan
        # On push to main, build or change infrastructure according to Terraform configuration files
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

     
